name: giselbook
description: A new Flutter project for hair salon services.

publish_to: 'none' # Rimuovi questa riga se vuoi pubblicare su pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Dipendenze Firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
